/**
 * SIG Questionnaire Exporter
 *
 * Generates a SIG-compatible .xlsx workbook from the implementations stored
 * in the Crosswalk database.
 *
 * NOTE: We use .xlsx (not .xlsm with macros) for maximum portability.
 * The original SIG template ships as .xlsm, but macro-enabled workbooks
 * require Excel and cannot be opened reliably in LibreOffice, Google Sheets,
 * or Numbers.  All response logic that previously relied on VBA macros is
 * replaced by static data-validation dropdowns and conditional formatting
 * achieved via ExcelJS cell styles.
 */

import * as path from 'path';
import ExcelJS from 'exceljs';
import Database from 'better-sqlite3';

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

export interface SigExportOptions {
  /** short_name of the SIG catalog to export (e.g. "sig-lite"). */
  catalogShortName: string;
  /** Optional scope name to filter implementations. */
  scopeName?: string;
  /** Export mode: pre-fill responses or leave blank for vendors. */
  mode: 'response-sig' | 'questionnaire';
  /** Absolute or relative path for the output .xlsx file. */
  outputPath: string;
  /** Organization name to pre-fill in Business Information sheet. */
  orgName?: string;
}

export async function exportSigQuestionnaire(
  options: SigExportOptions,
  db: Database.Database
): Promise<{ exported: number; outputPath: string }> {
  const { catalogShortName, scopeName, mode, outputPath, orgName } = options;

  // -------------------------------------------------------------------------
  // 1. Fetch controls + implementations
  // -------------------------------------------------------------------------
  interface SigRow {
    sig_question_number: string;
    question_text: string | null;
    sig_risk_domain: string | null;
    sig_control_family: string | null;
    sig_control_attribute: string | null;
    sig_scope_level: string | null;
    sig_response: string | null;
    additional_information: string | null;
    implementation_status: string | null;
    responsibility_type: string | null;
    scope_name: string | null;
  }

  // Build query — filter by catalog short_name and optionally scope
  const scopeJoin = scopeName
    ? `AND (s.name = ? OR i.scope_id IS NULL)`
    : '';
  const sql = `
    SELECT
      c.control_id         AS sig_question_number,
      c.description        AS question_text,
      c.sig_risk_domain,
      c.sig_control_family,
      c.sig_control_attribute,
      c.sig_scope_level,
      i.sig_response,
      i.statement          AS additional_information,
      i.status             AS implementation_status,
      i.responsibility_type,
      s.name               AS scope_name
    FROM controls c
    JOIN catalogs cat ON c.catalog_id = cat.id
    LEFT JOIN implementations i ON i.primary_control_id = c.id
    LEFT JOIN scopes s ON i.scope_id = s.id
    WHERE cat.short_name = ?
    ${scopeJoin}
    ORDER BY c.sort_order, c.control_id
  `;

  const queryParams: string[] = scopeName
    ? [catalogShortName, scopeName]
    : [catalogShortName];

  const rows = db.prepare(sql).all(...queryParams) as SigRow[];

  // -------------------------------------------------------------------------
  // 2. Build the workbook
  // -------------------------------------------------------------------------
  const workbook = new ExcelJS.Workbook();
  workbook.creator = 'Crosswalk';
  workbook.created = new Date();

  // -- Sheet 1: Copyright --------------------------------------------------
  const copyrightSheet = workbook.addWorksheet('Copyright');
  copyrightSheet.getCell('A1').value =
    'SIG Questionnaire — Generated by Crosswalk. ' +
    'Original SIG content belongs to Shared Assessments Group.';
  copyrightSheet.getColumn('A').width = 90;

  // -- Sheet 2: Instructions ------------------------------------------------
  const instructionsSheet = workbook.addWorksheet('Instructions');
  instructionsSheet.getColumn('A').width = 80;
  instructionsSheet.getCell('A1').value = 'Instructions';
  instructionsSheet.getCell('A1').font = { bold: true, size: 14 };
  [
    'Complete the SIG Questions worksheet by selecting a response from the dropdown in column D.',
    'Use column E (Additional Information) to provide supporting detail for each answer.',
    'Responses: Yes = control is in place, No = control is not in place, N/A = not applicable.',
    'Return the completed workbook to the requesting party.',
  ].forEach((line, i) => {
    instructionsSheet.getCell(`A${i + 3}`).value = line;
  });

  // -- Sheet 3: Dashboard --------------------------------------------------
  const dashboardSheet = workbook.addWorksheet('Dashboard');
  dashboardSheet.getColumn('A').width = 40;
  dashboardSheet.getColumn('B').width = 15;
  dashboardSheet.getColumn('C').width = 15;

  const headerFill: ExcelJS.Fill = {
    type: 'pattern',
    pattern: 'solid',
    fgColor: { argb: 'FFD9E1F2' },
  };

  ['Risk Domain', 'Total Questions', 'Responded'].forEach((h, i) => {
    const cell = dashboardSheet.getCell(1, i + 1);
    cell.value = h;
    cell.font = { bold: true };
    cell.fill = headerFill;
  });

  // Group rows by risk domain for the summary
  const domainMap = new Map<string, { total: number; responded: number }>();
  for (const row of rows) {
    const domain = row.sig_risk_domain ?? '(No Domain)';
    const entry = domainMap.get(domain) ?? { total: 0, responded: 0 };
    entry.total += 1;
    if (row.sig_response) entry.responded += 1;
    domainMap.set(domain, entry);
  }

  let dashRow = 2;
  for (const [domain, stats] of domainMap) {
    dashboardSheet.getCell(dashRow, 1).value = domain;
    dashboardSheet.getCell(dashRow, 2).value = stats.total;
    dashboardSheet.getCell(dashRow, 3).value = stats.responded;
    dashRow++;
  }

  // -- Sheet 4: Business Information ----------------------------------------
  const bizSheet = workbook.addWorksheet('Business Information');
  bizSheet.getColumn('A').width = 30;
  bizSheet.getColumn('B').width = 50;

  const bizFields: [string, string][] = [
    ['Organization Name', orgName ?? ''],
    ['Date', new Date().toLocaleDateString()],
    ['Scope', scopeName ?? ''],
    ['Catalog', catalogShortName],
  ];

  bizFields.forEach(([label, value], i) => {
    bizSheet.getCell(i + 1, 1).value = label;
    bizSheet.getCell(i + 1, 1).font = { bold: true };
    bizSheet.getCell(i + 1, 2).value = value;
  });

  // -- Sheet 5: SIG Questions -----------------------------------------------
  const sigSheet = workbook.addWorksheet('SIG Questions');
  _buildQuestionsSheet(sigSheet, rows, mode, false);

  // -- Sheet 6: Full (same layout, no grouping) -----------------------------
  const fullSheet = workbook.addWorksheet('Full');
  _buildQuestionsSheet(fullSheet, rows, mode, true);

  // -------------------------------------------------------------------------
  // 3. Write the workbook
  // -------------------------------------------------------------------------
  const resolvedPath = path.resolve(outputPath);
  await workbook.xlsx.writeFile(resolvedPath);

  return { exported: rows.length, outputPath: resolvedPath };
}

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

/** Row data shape from the DB query */
interface SigRow {
  sig_question_number: string;
  question_text: string | null;
  sig_risk_domain: string | null;
  sig_control_family: string | null;
  sig_control_attribute: string | null;
  sig_scope_level: string | null;
  sig_response: string | null;
  additional_information: string | null;
  implementation_status: string | null;
  responsibility_type: string | null;
  scope_name: string | null;
}

/**
 * Determines whether a question number represents a child control
 * (i.e., has 2 or more dots, such as "A.1.1").
 */
function isChildQuestion(questionNumber: string): boolean {
  return (questionNumber.match(/\./g) ?? []).length >= 2;
}

/**
 * Returns the ExcelJS Fill for a given implementation status.
 */
function statusFill(status: string | null): ExcelJS.Fill | undefined {
  switch (status) {
    case 'implemented':
      return { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFC6EFCE' } }; // light green
    case 'partially-implemented':
      return { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFFFEB9C' } }; // light yellow
    case 'not-applicable':
      return { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFD9D9D9' } }; // light gray
    default:
      return undefined; // white / no fill
  }
}

/**
 * Builds the SIG Questions worksheet structure.
 *
 * @param sheet    Target worksheet.
 * @param rows     Query result rows.
 * @param mode     'response-sig' pre-fills data; 'questionnaire' leaves columns D/E blank.
 * @param noGroup  When true, row grouping (outline) is not applied.
 */
function _buildQuestionsSheet(
  sheet: ExcelJS.Worksheet,
  rows: SigRow[],
  mode: 'response-sig' | 'questionnaire',
  noGroup: boolean
): void {
  // Column widths
  const colWidths = [35, 20, 55, 15, 50, 25, 25, 15, 20];
  colWidths.forEach((w, i) => {
    sheet.getColumn(i + 1).width = w;
  });

  // Header row
  const headers = [
    'Risk Domain',
    'Question Number',
    'Question / Request',
    'Response',
    'Additional Information',
    'Control Family',
    'Control Attribute',
    'Scope Level',
    'Status',
  ];

  const headerFill: ExcelJS.Fill = {
    type: 'pattern',
    pattern: 'solid',
    fgColor: { argb: 'FFD9E1F2' }, // light blue
  };

  const headerRow = sheet.getRow(1);
  headers.forEach((h, i) => {
    const cell = headerRow.getCell(i + 1);
    cell.value = h;
    cell.font = { bold: true };
    cell.fill = headerFill;
  });
  headerRow.commit();

  // Data rows
  rows.forEach((row, idx) => {
    const excelRow = sheet.getRow(idx + 2);
    const isChild = isChildQuestion(row.sig_question_number);

    // Col A: Risk Domain
    excelRow.getCell(1).value = row.sig_risk_domain ?? '';
    // Col B: Question Number (indent child questions)
    excelRow.getCell(2).value = isChild
      ? `  ${row.sig_question_number}`
      : row.sig_question_number;
    // Col C: Question / Request
    excelRow.getCell(3).value = row.question_text ?? '';
    // Col D: Response (pre-fill or leave blank)
    excelRow.getCell(4).value =
      mode === 'response-sig' ? (row.sig_response ?? '') : '';
    // Col E: Additional Information
    excelRow.getCell(5).value =
      mode === 'response-sig' ? (row.additional_information ?? '') : '';
    // Col F: Control Family
    excelRow.getCell(6).value = row.sig_control_family ?? '';
    // Col G: Control Attribute
    excelRow.getCell(7).value = row.sig_control_attribute ?? '';
    // Col H: Scope Level
    excelRow.getCell(8).value = row.sig_scope_level ?? '';
    // Col I: Status
    excelRow.getCell(9).value = row.implementation_status ?? '';

    // Data validation on the Response column (D)
    excelRow.getCell(4).dataValidation = {
      type: 'list',
      allowBlank: true,
      formulae: ['"Yes,No,N/A"'],
    };

    // Row color based on implementation status
    const fill = statusFill(row.implementation_status);
    if (fill) {
      for (let col = 1; col <= 9; col++) {
        excelRow.getCell(col).fill = fill;
      }
    }

    // Group child rows (outline level 1) when grouping is enabled
    if (!noGroup && isChild) {
      excelRow.outlineLevel = 1;
    }

    excelRow.commit();
  });
}
